name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to Main branch
        uses: actions/checkout@v2
      - name: Commit and Push new README.md to the repository
        uses: magnuscodus/magnuscodus@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
